language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: lGx+BTtqrmAwINdaAl1NLlEzxNTwhF96AsNXlAQbUGSf38eP6udrwoV2hMjpg94SQkJFabl3FaRxxdDqIDHKS4Z38e3Y5vpaISxGQsRpz09+31Ch8dcDIOF6CN+Gpcd5+A+vFfyohNbnAzIss4rFTNaWxxW0t/fDO6qcGqidcvHFufPRsjchTgGo+HKaEDR/Am/bC1pIWFvBnks3GBQVeF35wIMuM7bRRz4gnISXLkvJsHW8VVqpg5pFI73ObkRu9zB6SkIer0p5p+cysNUkJwPSA1FAzRIOiF/n/SJ5ilCHFVFLl0WQiCYqSS26v9SI7mhMxqrgINLSB0MPJuBqDFePvV/Qou5sMuBPk6eKmkcSsNa6UY8x3jsyJWQeFV/7R9GpxcVgKbVFO1fFZfas41YdkopP3GNhBvFhbgPbIj5s+WPD6uG/F3mBfG76lvq86HlbIzjoHECkNDhLZlwdk3eIDCp+EZbJUY8PpHHzos+Gbv5IO0akAWmB6vF+HgfdMIgoQqtF0LYLSSTjSRfuAdkfiM3ZsQLbak41nL3EegXyvJV82+dEq6sY/eNLkjsBwsp+43Y2utx03m2oAVQtckqwsvHDB15uwIR4Wu0RoMy5Y4ZHFUt/xbJTjWY2mUNUTL4GuxWxzBDWjIrg9AZxaRR7Oyui6Mt15eypmrumCkM=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: VtWj1g0SyNtXtA1A4vF/nNHzDe+cfkld7VfQsUEAlrz0Ux9geKPuV2qCeJ8v8ZZICc5v2ubLJI5Zx6MSrh1ScN9IQh4mEa9gBi7JvB/Ww8R9dugT5ZemTmqK01A/mygerE/F8ryPm+JtMhscPFDJjvYBHaZi8IRx9XngKgyA2gUj1W6jXH89oebA6B+3o87ulfwDQjxL/LiWbfGpzCUH7CWLDRXsAE+w/Bi+e0g++LECoxn4kVbQY0iNE0K3N8TB+KvMkwPDSXUA20pFnWeUhpkLtw5qhuezksr6ZqbVCzJNdrUjaAEkA4eXX3p2JTK3H30jwMjXoOc3gciDbwPnsuSZXPIJ/8CUc/7nyZeiuLJqw44tzFviS0VlDXu4rh4EeS+yfd/6Y63ukRdpdMVO7yRMO6vXQOImSS6taEEuc2bCkzYfbRT5Jy81vlNQO/gAKgXO2gF01x+sZt6Pk702spzHjDqkKhR+Z/plZa8aupCPvMeMmatFcWvPR5R39mLQ7o1G688NbmeQGPrdiVtfclYG1vbBKDu8/m0khKWHe5inc7agi1suShGEYbhQXdo1hXuvs8m4K6AwbJ5mBvYqTjRF1Y9WZleDkpKFpeLzHI83Mk3NipRIY6lANdZ/Sm4XaReTzoSp3jDjr26IvUACE+LFaIsysVsA4AD21gXk7AI=
  - secure: eTaANWNd9QUcV9JpJVZd3aRRyapHU5BUYzk2xyG8k/FAi6ItEUoyU+1F7DKjBiQZIcsANqEgkInk13DrKb/daayywhWPeGkJ8Dl2qihsasXFiU8ncvjckjJxUjkxEIr5dNzs214Jp7K5HA3PSygvDCmJpYhAWBGlE5Dj4ltjUk6nC6bySqaaIeF/xfzrvWiWzIFOm837N+LcC6O72cwNao0qYZ0aDHD9JID+Rqea4qHQe4vfX8e0Im42xGgOl2rnXtwETQwJRMyJEyAcvhwannUNHMKNVJ3tSsblmIKdUm/ZWRDxkxZJFW/7w1vU61LSx9bT0IgU6BWF0sVA2qLwBhxK/NGkBoW0g+lrAYvtcLYTAh8lWURX4dMcEpAQYmPQzuJTr0+zrCEPJh59MNRRaGap10DYCxGDbUrv3whoNvuvB95dNRcepaZ5eTPSRy6To/bo6QvPaurct9QS79Aw7mizrwbAJmkAg8BpN7lmOJGHTnBKO+Uh8anIx9xvkBP9ciVN/BwC6QuHjW1J4GYDtstZTy5HoQE1vmiV4RWvjL6HMwxifJ3LQW6qfLfm+GFGomzURb2MgZhxJKNEx1tI+pA4HiOjKDHBT2LfR4taJ/d4anSyadKNX3NPp7sHbaAhw//k8AX3uX7j7A16kg8WInrVtCM4YDQMThPETaoZxak=
 matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-enci-service:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
