#Default port is 8091
server:
  port: 8091
  
spring:
  cloud:
    stream:
      bindings:
        inboundDogChanges:
          destination: dogDogTopic
          content-type: application/json
          group: dogGroup
        inboundOwnerChanges:
          destination: ownerDogTopic
          content-type: application/json
          group: dogGroup
        inboundBreederChanges:
          destination: breederDogTopic
          content-type: application/json
          group: dogGroup
        inboundTitleChanges:
          destination:  titleDogTopic
          content-type: application/json
          group: dogGroup
        inboundPedigreeChanges:
          destination:  pedigreeDogTopic
          content-type: application/json
          group: dogGroup
        inboundParentChanges:
          destination:  parentDogTopic
          content-type: application/json          
          group: dogGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
                
#Setting the logging levels for the service
#Migrate to logstach and Cloud Config
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.scc: DEBUG   
#    org.apache.kafka: WARN   
